### ISSUE TITLE
Router crashes on marathon ConnectException

### ISSUE THREAD

**Issue by pschorf** [twosigma/waiter#172]
A ConnectException thrown at https://github.com/twosigma/waiter/blob/master/waiter/src/waiter/scheduler.clj#L348 causes the router to crash. The fix is probably to extend https://github.com/twosigma/waiter/blob/master/waiter/src/waiter/scheduler.clj#L107 to support ConnectException in addition to checking for 5xx status codes.

**Comment by shamsimam** [comment]
Closing as the issue has been resolved.
