### ISSUE TITLE
/waiter-async endpoints should not propagate authorization header to backend

### ISSUE THREAD

**Issue by dposada** [twosigma/waiter#80]
They currently pass along whatever authorization header was provided by the client. This was discovered when some of our tests attempted to pass the authorization header on /waiter-async routes, and the header was forwarded to kitchen, which then failed to authenticate because it expects the `WAITER_USERNAME` and `WAITER_PASSWORD` it was configured with.

**Comment by shamsimam** [comment]
This was resolved by the choice of removing hop-by-hop headers.
